pam_script_is_work

diff --git a/vagrantfile b/vagrantfile
--- a/vagrantfile
+++ b/vagrantfile
@@ -13,10 +13,31 @@ Vagrant.configure("2") do |config|
                    ip: "192.168.56.11",
                    auto_config: true
 
-    srv.vm.provision "shell", inline: <<-SHELL
+      # Создаем заранее подготовленный скрипт
+      srv.vm.provision "shell", inline: <<-SHELL
+      cat >> /usr/local/bin/login.sh << 'EOF'
+#!/bin/bash
+#Первое условие: если день недели суббота или воскресенье
+if [ $(date +%a) = "Sat" ] || [ $(date +%a) = "Sun" ]; then
+ #Второе условие: входит ли пользователь в группу admin
+ if getent group admin | grep -qw "$PAM_USER"; then
+        #Если пользователь входит в группу admin, то он может подключиться
+        exit 0
+      else
+        #Иначе ошибка (не сможет подключиться)
+        exit 1
+    fi
+  #Если день не выходной, то подключиться может любой пользователь
+  else
+    exit 0
+fi
+EOF
+SHELL
+    
+      srv.vm.provision "shell", inline: <<-SHELL
       set -e
 
-      # Включаем парольную аутентификацию через drop-in (перебивает Include)
+      # Включаем парольную аутентификацию 
 #      echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
 #      echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
       sed -i 's/^#PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
@@ -37,6 +58,13 @@ Vagrant.configure("2") do |config|
       usermod -aG admin otusadm
       usermod -aG admin root
       usermod -aG admin vagrant
+      
+      # Делаем файл login.sh исполняемым
+      chmod +x /usr/local/bin/login.sh   
+
+      # Укажем в файле /etc/pam.d/sshd модуль pam_exec и наш скрипт:
+      #sed -i 's|^auth required.*$|auth required pam_exec.so debug /usr/local/bin/login.sh|' /etc/pam.d/sshd
+      echo "auth required pam_exec.so debug /usr/local/bin/login.sh" >> /etc/pam.d/sshd
     SHELL
   end
 end
